<a href="https://colab.research.google.com/github/001010/GoogleColab_AI_Vision/blob/main/lesson_1_1_challenge_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

# YOUR TURN: Create a function that:
# 1. Takes an image array
# 2. Increases brightness by a given percentage
# 3. Ensures values stay in 0-255 range
# 4. Returns the modified image

def adjust_brightness(image, percentage):
    # Your code here:
    image = image * (percentage / 100)
    image = np.clip(image, 0, 255)  # Keep in valid range
    return image

# Test your function:
test_image = np.random.randint(0, 256, size=(100, 100))
bright_image = adjust_brightness(test_image, 130)  # 30% brighter


print(test_image)

print(f"\n{bright_image}")


[[ 35   6  68 ...  75 155 171]
 [204 239 228 ...  28 200   8]
 [ 70 242  61 ...  46 129 196]
 ...
 [ 21 206 161 ...  32 233  62]
 [ 10 114  97 ...  61 232 203]
 [ 32  95 114 ...  78 178  87]]

[[ 45.5   7.8  88.4 ...  97.5 201.5 222.3]
 [255.  255.  255.  ...  36.4 255.   10.4]
 [ 91.  255.   79.3 ...  59.8 167.7 254.8]
 ...
 [ 27.3 255.  209.3 ...  41.6 255.   80.6]
 [ 13.  148.2 126.1 ...  79.3 255.  255. ]
 [ 41.6 123.5 148.2 ... 101.4 231.4 113.1]]
